# Generated by Django 4.0.3 on 2022-03-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
