# Generated by Django 4.0.3 on 2022-03-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('sale_price', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('purchase_date', models.DateTimeField()),
                ('sell_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'PRODUCT',
            },
        ),
    ]
